name: build_alpine_docker_image
run-name: Build a alpine docker image
on: [push]
jobs:
  build-alpine-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: false
          load: true
          tags: |
            alpine:local

      - name: Save image
        run: docker save alpine:local | gzip > alpine_local.tar.gz

      - name: List image
        run: docker images && ls -l *.tar.gz
      
      - name: Upload image to cloudflare
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: image
          source-dir: /home/runner/work/workflow/workflow
          destination-dir: workflow # Can be anything as long as it is an actual path
          output-file-url: 'true' # defaults to true
