name: build_docker_image
run-name: Build a docker image
on: 
  push:
    paths:
      - 'docker_build/**.env'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: output
        id: output
        run: (git log -p -1 | grep diff | awk '{print $NF}' | awk -F'/' '{print $2"/"$3}' | xargs cat)>> $GITHUB_OUTPUT

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{steps.output.outputs.docker_file_path}}
          platforms: linux/amd64
          push: false
          load: true
          tags: ${{steps.output.outputs.docker_tag}}

      - name: Save image
        run: docker save ${{steps.output.outputs.docker_tag}} | gzip > ${{steps.output.outputs.docker_image_name}}.tar.gz

      - name: List image
        run: docker images && ls -l *.tar.gz
      
      - name: Upload image to cloudflare
        uses: randomairborne/r2-release@v1.0.2
        with:
          endpoint: ${{secrets.R2_END_POINT}}
          accesskeyid: ${{ secrets.R2_ACCESS_KEY_ID }}
          secretaccesskey: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          bucket: image
          file: ${{steps.output.outputs.docker_image_name}}.tar.gz
          destination: /docker/${{steps.output.outputs.docker_image_name}}.tar.gz
