name: build_rpi_openwrt_image
run-name: Build a Openwrt image for rpi
on: workflow_dispatch
jobs:
  build-openwrt-rpi-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Build openwrt image
        uses: izer-xyz/openwrt-imagebuilder-action@v6
        with:
          image: bcm27xx-bcm2708
          openwrt-version: 23.05.2
          packages: vim zerotier tmux tcpdump netcat ip-full ss nftables openssh-server |
            -ip-tiny -iptables -ip6tables -dnsmasq -ppp -ppp-mod-pppoe -iw -iwinfo -wpad-basic-mbedtls -odhcpd-ipv6only -odhcp6c -dropbear
          profile: rpi
          rootfs: 800
          disabled-services: firewall

      - name: List image
        run: ls  -l bin/*.img.gz
