name: build_rpi_openwrt_image
run-name: Build a Openwrt image for rpi
on: workflow_dispatch
jobs:
  call-docker-build:
    uses: zhenggc1/workflow/.github/workflows/build_openwrt_image.yaml@main
    with:
      openwrt_image: bcm27xx-bcm2708
      openwrt_version: 23.05.2
      openwrt_profile: rpi
      openwrt_root_size: 800
