name: template_of_build_docker_image
run-name: Build a docker image
on: 
  workflow_call:
    inputs:
      docker_file_path:
        required: true
        type: string
      docker_tag:
        required: true
        type: string
      docker_image_name:
        required: true
        type: string
    secrets:
      R2_END_POINT:
        required: true
      R2_ACCESS_KEY_ID:
        required: true
      R2_SECRET_ACCESS_KEY:
        required: true

jobs:
  build-alpine-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{inputs.docker_file_path}}
          platforms: linux/amd64
          push: false
          load: true
          tags: ${{inputs.docker_tag}}

      - name: Save image
        run: docker save ${{inputs.docker_tag}} | gzip > ${{inputs.docker_image_name}}.tar.gz

      - name: List image
        run: docker images && ls -l *.tar.gz
      
      - name: Upload image to cloudflare
        uses: randomairborne/r2-release@v1.0.2
        with:
          endpoint: ${{secrets.R2_END_POINT}}
          accesskeyid: ${{ secrets.R2_ACCESS_KEY_ID }}
          secretaccesskey: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          bucket: image
          file: ${{inputs.docker_image_name}}.tar.gz
          destination: /docker/${{inputs.docker_image_name}}.tar.gz
