name: docker_image_download_and_upload_to_cf
run-name: download a docker image and update to cloudflare

on: 
  label:
    types: created

jobs:
  download-docker-image-and-update-to-cf:
    runs-on: ubuntu-latest
    env:
      docker_tag: def
      docker_image_name: abc

    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull image
        run: docker pull ${{docker_tag}}

      - name: Save image
        run: docker save ${{docker_tag}} | gzip > ${{docker_image_name}}.tar.gz

      - name: List image
        run: docker images && ls -l *.tar.gz
      
      - name: Upload image to cloudflare
        uses: randomairborne/r2-release@v1.0.2
        with:
          endpoint: ${{secrets.R2_END_POINT}}
          accesskeyid: ${{ secrets.R2_ACCESS_KEY_ID }}
          secretaccesskey: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          bucket: image
          file: ${{docker_image_name}}.tar.gz
          destination: /docker/${{docker_image_name}}.tar.gz
