name: test_github_output
run-name: Test Github Output
on: workflow_dispatch

jobs:
  test-github-outpu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: output
        id: output
        run: cat kv.txt >> $GITHUB_OUTPUT

      - name: echo
        run: echo ${{steps.output.outputs.a}}
          echo ${{steps.output.outputs.c}}

