name: test_github_output
run-name: Test Github Output

on: 
  push:
    paths:
      - 'test/**.env'

jobs:
  test-github-output:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: output
        id: output
        run: git log -n 2 | grep commit | awk '{print $2}' | xargs git diff | grep diff | awk '{print $NF}' | awk -F'/' '{print $2"/"$3}' | xargs cat

      - name: test_output
        run: echo $GITHUB_OUTPUT && echo ${{steps.output.outputs.a}}


