name: test_github_output
run-name: Test Github Output

on: 
  push:
    paths:
      - 'test/**.env'

jobs:
  test-github-outpu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: output
        id: output
        run: echo ${{github.event.head_commit.modified}}


