name: test_github_output
run-name: Test Github Output

on: 
  push:
    paths:
      - 'test/**.env'

jobs:
  test-github-output:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: output
        id: output
        run: pwd && git log -n 1 && (git log -n 2 --format=%H)

      - name: test_output
        run: echo $GITHUB_OUTPUT && echo ${{steps.output.outputs.a}}


